diary/urls.py
from django.urls import path
from .import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), #/diary
    #汎用ビューを使用する際には、as_view()を記載しなければならない。
    path('add/', views.AddView.as_view(), name='add'), #/diary/add
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

diary/models.py
from django.db import models
from django.utils import timezone #djangoではdatetime.nowの代わりにtimezone.nowを使う


class Day(models.Model):
    title = models.CharField('タイトル', max_length=200)
     #CharFieldは一行で収まる物(titleなど、、、)
    text = models.TextField('本文')
     #TextFieldは複数行の文字列に保存したいものに使う
    date = models.DateTimeField('日付', default=timezone.now)
     #DateTimeFieldは日付と時間を扱うもの
     
    def __str__(self):
         return self.title

'''
    モデルを作成したらプロンプトにてデータベースに反映する必要がある。
        py manage.py makemigrations diary
            migrationは移動という意味
            このコマンドでdjangoフレームワークに作成や変更したよと伝えている。

        py manage.py migrate
            migrateをすることで実際に反映を行う。
            
'''

diary/forms.py
from django import forms #django内のformsメソッドをインポートする
from .models import Day #diaryフォルダ内のmodels.pyのクラスDayを呼び出す


class DayCreateForm(forms.ModelForm): #formsクラスのModelFormメソッドを使う(継承)。
    """ModelFormはあらゆる起こりうるエラーやインプットなどの記載しなければいけないことを
            簡易的にしてくれるメソッドアイテム
            この場合Dayクラスに記載している内容から自動的に処理をしてくれる
            formメソッドを継承する場合にはformに記載していかなければならない"""

    class Meta:
        model = Day #class Dayをmodel変数に代入　←　対象
        """Dayをもとにモデルを作成する"""
        fields = '__all__'
        """どこのフィールド(title, text, dateなど)"""

diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day

class IndexView(generic.ListView):
    model = Day
    paginate_by = 3

class AddView(LoginRequiredMixin, generic.CreateView):
    model = Day
    form_class = DayCreateForm #カスタマイズしたクラスformを使用
    #fields = '__all__'で汎用ビューで単純なモデルの場合はこれで作成できる。→forms.pyを省ける。
    success_url = reverse_lazy('diary:index')

class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')
        
class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Day
    success_url = reverse_lazy('diary:index')

class DetailView(generic.DetailView):
    model = Day
    

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>日記アプリケーション</title>

    {% block extracss %}{% endblock %}
    <!--↑はcssの上書き処理-->
  </head>
  <body>
    <div class = "container">
      <nav class="nav">
        <a clasd="nav-link" href="{% url 'admin:index' %}">ログイン</a>
      
        <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
        
        {% if user.is_superuser %}
        <a class="nav-link" href="{% url 'diary:add' %}" target="_blank">追加</a>
        {% endif %}
        <!--注意: urlの記載の後に必ず空白を入れないとエラーが起こる。 -->
      </nav>
      {% block content %}
      {% endblock %}
    </div>
    
    <!--↑は上書きできるcontentタグ-->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    {% block extrajs %}{% endblock %}
    <!--↑はjsの上書き可能処理-->
  </body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class='table'>
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
<button type="submit" class="btn btn-primary">送信</botton>
{% csrf_token %}　
</form>
{% endblock %}

diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}

    <!--
        (action=)はこれに対し書いたurlに対しデータを送信するか、または
    ""←のように空文字にすると今現在いるurlに対してデータを扱うかということになる。
        (method=)はこれに対してどのようにデータをするか
        2パターンありPOST　か　GET である
        POSTに関してはデータを内部的に扱う方法
        GETに関してはデータを公開できる状態であること(例amazonなどの商品ページなど)
    -->
    <table class='table'>
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text | linebreaksbr }}</td>
            <!--djangoの機能→　| linebreaksbrとすることで本文参照時、改行を行う-->
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>
<!--form.as_pと置くことで自動的にDayモデルの内容から生成してくれる-->

{% endblock %}

<!--<form>内のボタンサブミットによってサーバーにデータを与える仕組み-->

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<p>{{ day.title }}</p>
<form action="" method="POST">
    <!--
        (action=)はこれに対し書いたurlに対しデータを送信するか、または
    ""←のように空文字にすると今現在いるurlに対してデータを扱うかということになる。
        (method=)はこれに対してどのようにデータをするか
        2パターンありPOST　か　GET である
        POSTに関してはデータを内部的に扱う方法
        GETに関してはデータを公開できる状態であること(例amazonなどの商品ページなど)
    -->
    <table class='table'>
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>
<!--form.as_pと置くことで自動的にDayモデルの内容から生成してくれる-->
<button type="submit" class="btn btn-primary">送信</botton>
    <!--btn btn-primaryはボタンの見た目を変えている。-->
{% csrf_token %}　<!--POSTに対しては必須であるものでセキュリティに対する構文である-->
</form>
{% endblock %}

<!--<form>内のボタンサブミットによってサーバーにデータを与える仕組み-->

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
            <td>{{ day.date }}</td>
            
            <td>
                {% if user.is_superuser %}
                <a href="{% url 'diary:update' day.pk %}" target="_blank">更新</a>
                {% endif %}
            </td>
            
            <td>
                {% if user.is_superuser %}
                <a href="{% url 'diary:delete' day.pk %}" target="_blank">削除</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!--前へ　の部分-->
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

    <!--次へ　の部分-->
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}  
{% endblock %}